### ISSUE TITLE
New web player breaks getElementById

### ISSUE THREAD

**Issue by jjbankert** [beaufortfrancois/spotify-hotkeys-chrome-extension#11]
The extension broke with the new web player.
The `div` with buttons now looks like this for me:
```
<div class="buttons">
  <button class="control-button spoticon-shuffle-16" title="Enable shuffle">
    ::before
  </button>
  <button class="control-button spoticon-skip-back-24" title="Previous">
    ::before
  </button>
  <button class="control-button spoticon-pause-32" title="Pause">
    ::before
  </button>
  <button class="control-button spoticon-skip-forward-24" title="Next">
    ::before
  </button>
  <button class="control-button spoticon-repeat-16" title="Enable repeat">
    ::before
  </button>
</div>
```

I'm unsure what the numbers depend on but maybe it can be caught with a regex for robustness

**Comment by beaufortfrancois** [comment]
I've just pushed https://github.com/beaufortfrancois/spotify-hotkeys-chrome-extension/commit/a372fc50eb2e283c0a31d30a869feb46332a159d to support https://open.spotify.com web player. Check out new version at https://chrome.google.com/webstore/detail/spotify-web-player-hotkey/kimlaecdbfehihbiieeaeelbdkahophn and let me know if that works out for you ;)

**Comment by jjbankert** [comment]
Confirmed working, thanks for the quick response!
