### ISSUE TITLE
Overbroad permissions to https://*.spotify.com/*

### ISSUE THREAD

**Issue by fredcadete** [beaufortfrancois/spotify-hotkeys-chrome-extension#12]
#10  , supporting open.spotify.com (thanks a lot BTW) asks for permissions to all sites under spotify.com. Chrome is giving a notification of this upon update.

This is very broad. I suppose it would allow the extension to view my payment info, which is managed under www.spotify.com

Any chance that it can be changed to play.spotify.com|open.spotify.com or something similar?

**Comment by beaufortfrancois** [comment]
You're absolutely right.
Let me fix that!

**Comment by beaufortfrancois** [comment]
I've just fixed that in https://github.com/beaufortfrancois/spotify-hotkeys-chrome-extension/commit/c06f8ac765042945c32eff2ed2ac1ba2a054c370 and pushed an update to https://chrome.google.com/webstore/detail/kimlaecdbfehihbiieeaeelbdkahophn
