### ISSUE TITLE
Save Track issue

### ISSUE THREAD

**Issue by atos93** [beaufortfrancois/spotify-hotkeys-chrome-extension#15]
hi after new update save track don't work anymore

i think this can fix the issue
`
 case 'shuffle': code = 'document.querySelector(".spoticon-add-16").click()'; break;`

**Comment by MartinLichtblau** [comment]
Yes, saving a track doesn't work anymore with the new Spotify UI.
@beaufortfrancois

**Comment by beaufortfrancois** [comment]
Thank you @atos93 and @MartinLichtblau!
I've just pushed an update.
See https://github.com/beaufortfrancois/spotify-hotkeys-chrome-extension/compare/a7b7c3b...master
