### ISSUE TITLE
Add new hotkeys {Resolved

### ISSUE THREAD

**Issue by ghost** [beaufortfrancois/spotify-hotkeys-chrome-extension#18]
Hello,

first of all, Thanks! I was look for this hotkeys a long time!

second, can I set new hotkeys? 
for example, my keyboard have support to play/pause and anothers keys and I would like to define them.

again, Thanks

regards

**Comment by beaufortfrancois** [comment]
I believe you can configure them by clicking on "Keyboard shortcuts" at the very bottom of the `chrome://extensions` page such as:

![screenshot 2017-07-05 at 8 26 32 am](https://user-images.githubusercontent.com/634478/27851581-b661f2ea-615b-11e7-993b-73aa9a19755b.png)

**Comment by ghost** [comment]
Thanks!
