### ISSUE TITLE
It does not work on OSX

### ISSUE THREAD

**Issue by trocotronic** [beaufortfrancois/spotify-hotkeys-chrome-extension#2]
Hi,

I am using OSX 10.10 and latest Chrome. Whereas in Windows works perfectly, in OSX 10.10 previous and next tracks do not work. The only key that works is play/pause.

**Comment by beaufortfrancois** [comment]
Can you go to _chrome://extensions_, scroll to the very bottom of the page, click on "Keyboard shortcuts" and see if you have updated somehow Spotify Web Player Hotkeys for these specific actions?

**Comment by trocotronic** [comment]
Sorry for the delay.
Yes, all shortcuts are displayed. alt+shift+p/./, but only works p.
Thanks for the reply.

**Comment by beaufortfrancois** [comment]
Argh, it looks like it's a known chrome issue. 
You might want to star http://crbug.com/497188
