### ISSUE TITLE
Skip+Previous Track will jump two songs (instead of one)

### ISSUE THREAD

**Issue by wle8300** [beaufortfrancois/spotify-hotkeys-chrome-extension#21]
Seems to register twice whenver you use hotkeys for skip+previous track.

So it'll skip two songs instead of one (as expected)

----

I'm using Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by beaufortfrancois** [comment]
I can't reproduce ;(

1. Go to https://open.spotify.com/user/spotify/playlist/37i9dQZF1DX0QqahDuqmRY
2. Start playing audio
3. Press Alt+Shift+Period to skip song
4. It goes to the second song, not the third one

**Comment by wle8300** [comment]
Hmm. Maybe it’s related to another extensions I’m using… I have a lot of extensions installed. I’ll have to get back to you once I figure it out.

Oh yea. This extension totally rocks. Thanks for making it! I use it everyday! :P

**Comment by simontb** [comment]
I faced the same issue with two Spotify Tabs open. Looking at your code I am not sure whether this is an issue or intended behavior.

**Comment by DiegoAstiazaran** [comment]
Same thing is happening to me. I'm using Chrome version 74.0.3729.159 on ChromeOS 11895.

**Comment by beaufortfrancois** [comment]
If you have two tabs, it makes sense since commands are sent to all tabs: https://github.com/beaufortfrancois/spotify-hotkeys-chrome-extension/blob/f6c5c2ed1e6e2abac79fa1a11322da89fd1dead8/src/background.js#L9
