### ISSUE TITLE
"Save Track" broken

### ISSUE THREAD

**Issue by MartinLichtblau** [beaufortfrancois/spotify-hotkeys-chrome-extension#23]
The save function does not work anymore. Spotify changed the appearance of that function (now a heart button) and likely they changed more than that. 

I tried: different shortcuts, uninstalling, ...
Anyone else?

**Comment by beaufortfrancois** [comment]
You're right. It is now `spoticon-heart-16`. I'll update the extension shortly.

Thanks for reporting this @MartinLichtblau

**Comment by beaufortfrancois** [comment]
And it is fixed now in 0.5.3! See https://github.com/beaufortfrancois/spotify-hotkeys-chrome-extension/commit/26da965dfe318f41a460be27df4bfc23111416ff
https://chrome.google.com/webstore/detail/kimlaecdbfehihbiieeaeelbdkahophn/
