### ISSUE TITLE
Can't set Media Keys as Shortcuts

### ISSUE THREAD

**Issue by greenbigfrog** [beaufortfrancois/spotify-hotkeys-chrome-extension#4]
Hi!
I can't set my Media Keys as Shortcuts. I'm running chromium on Ubuntu.

Maybe you can help me...

**Comment by beaufortfrancois** [comment]
It looks like it's a known issue on Ubuntu.
See https://code.google.com/p/chromium/issues/detail?id=451510

**Comment by greenbigfrog** [comment]
Ok... Thanks for your work!

**Comment by gibsson** [comment]
Hi,

Sorry to revive an old thread/issue. François, do you know if the same issue exist on Chrome (not Chromium)? I can't find any reference of it.
My system is a Linux Debian with Chrome 50.0.2661.102 64-bit and the icon is always grey'ed out, can't even access the options.
I've seen other comments/pull requests saying that the url changed to player.spotify but in my case it is play.spotify as defined in the source code.

Thanks!

**Comment by beaufortfrancois** [comment]
@gibsson It works great for me on Google Chrome - Ubuntu 14.04 LTS.
There are no "options". However you can customize shortcuts: go to `chrome://extensions` and at the very bottom click "Keyboard shortcuts" link and you should see them.

![screenshot from 2016-06-27 08_38_40](https://cloud.githubusercontent.com/assets/634478/16370838/0fd67998-3c43-11e6-8010-7480c5a65f59.png)

**Comment by gibsson** [comment]
You're right, I didn't see the "keyboard shorcuts" link before. Thanks!
